force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAN-{000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Candidate&#39;s status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Validated by HR</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <displayFormat>V-{000}</displayFormat>
        <label>Vacancy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Candidate proposed for this vacancy by recruiter (Only candidates with &quot;Validated by HR&quot; status)</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/VacancyCandidateAssociation__c.object-meta.xml
<CustomObject>
    <label>VacancyCandidateAssociation</label>
    <nameField>
        <displayFormat>VCA-{0000}</displayFormat>
        <label>VacancyCandidateAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VacancyCandidateAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Vacancy__c.field-meta.xml
<CustomField>
    <fullName>Vacancy__c</fullName>
    <label>Vacancy</label>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestAssignCandidates.cls
@isTest
public class TestAssignCandidates {
    static AssignCandidatesController assignCandidatesController;
    static Vacancy__c[] vacancies;
    static PageReference pref;
    static Candidate__c[] candidates;
    static List<String> selectedCandidates = new List<String>();

    private static void init() {
        String vacancyStatus = RecruitingAppConstants.INPROGRESS_STATUS;
        String candidateStatus = RecruitingAppConstants.VALIDATED_STATUS;
        vacancies = TestDataFactory.createVacancies(1, vacancyStatus);
        candidates = TestDataFactory.createCandidates(3, candidateStatus);

        for (Candidate__C candidate : candidates) {
            selectedCandidates.add(candidate.Id);
            candidate.Status__c = candidateStatus;
        }

        update candidates;

        TestDataFactory.createVca(vacancies[0].Id, candidates[0].Id);

        pref = new PageReference('/' + vacancies[0].Id);
        pref.getParameters().put('id', vacancies[0].Id);
        Test.setCurrentPage(pref);

        ApexPages.StandardController stdCtr = new ApexPages.StandardController(vacancies[0]);
        assignCandidatesController = new AssignCandidatesController(stdCtr);
        assignCandidatesController.selectedCandidates = selectedCandidates;
    }

    @isTest
    private static void testGetCandidates() {
        List<SelectOption> options = new List<SelectOption>();

        init();
        Test.startTest();
        options = assignCandidatesController.getCandidates();
        System.assertEquals(2, options.size());

        Test.stopTest();

    }

    @isTest
    private static void TestAssignCandidates() {
        init();
        Test.startTest();
        assignCandidatesController.assignCandidatesAction();

        String vacancyId = vacancies[0].Id;
        VacancyCandidateAssociation__c[] vca = [
                SELECT Id
                FROM VacancyCandidateAssociation__c
                WHERE Vacancy__c = :vacancyId
                AND Candidate__c IN :selectedCandidates
        ];
        System.assertEquals(true, vca.size() > 0);

        Test.stopTest();
    }
}