force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAN-{000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>FirstName__c + &#39; &#39; +  LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <displayFormat>V-{000}</displayFormat>
        <label>Vacancy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Candidate proposed for this vacancy by recruiter (Only candidates with &quot;Validated by HR&quot; status)</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/VacancyCandidateAssociation__c.object-meta.xml
<CustomObject>
    <label>VacancyCandidateAssociation</label>
    <nameField>
        <displayFormat>VCA-{0000}</displayFormat>
        <label>VacancyCandidateAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VacancyCandidateAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Vacancy__c.field-meta.xml
<CustomField>
    <fullName>Vacancy__c</fullName>
    <label>Vacancy</label>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CloseVacancyController.cls
public with sharing class CloseVacancyController {
    private Vacancy__c vacancy;
    public String candidate { get; set; }
    public String inProgressStatus {
        get {
            return RecruitingAppConstants.INPROGRESS_STATUS;
        }
    }
    public String cantCloseText {
        get {
            return RecruitingAppConstants.CANT_CLOSE_TEXT;
        }
    }
    public String noCandidatesText {
        get {
            return RecruitingAppConstants.NO_CANDIDATES_TO_CLOSE_TEXT;
        }
    }

    public CloseVacancyController(ApexPages.StandardController standardController) {
        this.vacancy = (Vacancy__c) standardController.getRecord();
    }

    public PageReference closeVacancy() {
        Map<String, String> flowParams = new Map<String, String>();
        flowParams.put('varVacancyId', vacancy.id);
        if (string.isNotBlank(candidate)) {
            // Close vacancy if candidate exists
            // Run Close flow
            flowParams.put('varCandidateId', candidate);
            Flow.Interview.Close_Vacancy closeVacancy = new Flow.Interview.Close_Vacancy(flowParams);
            closeVacancy.start();
        } else {
            // Cancel vacancy if candidate doesn't exist
            // Run Cancel Flow
            system.debug(candidate);
            Flow.Interview.Cancel_Vacancy cancelVacancy = new Flow.Interview.Cancel_Vacancy(flowParams);
            cancelVacancy.start();
        }

        // Redirect back to Vacancy page
        PageReference page = new PageReference('/' + vacancy.id);
        page.setRedirect(true);
        return page;
    }

    public List<SelectOption> getCandidates() {
        List<SelectOption> candidatesOptions = new List<SelectOption>();

        Id vacancyId = vacancy.id;
        // Get all related candidates available for approve
        for (VacancyCandidateAssociation__c vacancyCandidates : [
                SELECT Id, Candidate__r.Id, Candidate__r.Full_Name__c
                FROM VacancyCandidateAssociation__c
                WHERE Vacancy__c = :vacancyId
        ]) {
            candidatesOptions.add(new SelectOption(vacancyCandidates.Candidate__r.Id, vacancyCandidates.Candidate__r.Full_Name__c));
        }

        return candidatesOptions;
    }
}